/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class Beranda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalSiswa = new javax.swing.JLabel();
        totalKelas = new javax.swing.JLabel();
        jmlhJurusan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalSiswa.setForeground(new java.awt.Color(0, 51, 51));
        totalSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSiswa.setText("0");
        getContentPane().add(totalSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, -1));

        totalKelas.setForeground(new java.awt.Color(0, 51, 51));
        totalKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKelas.setText("0");
        getContentPane().add(totalKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 40, -1));

        jmlhJurusan.setForeground(new java.awt.Color(0, 51, 51));
        jmlhJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlhJurusan.setText("0");
        getContentPane().add(jmlhJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/beranda.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        setBounds(0, 0, 926, 542);
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Angkatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Angkatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Angkatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Angkatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jmlhJurusan;
    private javax.swing.JLabel totalKelas;
    private javax.swing.JLabel totalSiswa;
    // End of variables declaration//GEN-END:variables
}
