/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JOptionPane;
import koneksi.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;


/**
 *
 * @author Hafiz
 */

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    Koneksi koneksi = new Koneksi();
    Color DefaultColor, DefaultColor2, ClickedColor, ClickedColor2;
    
    public Dashboard() {
        initComponents();
        
        DefaultColor = new Color(25,72,77);
        DefaultColor2 = new Color(255,255,255);
        ClickedColor = new Color(45,116,124);
        ClickedColor2 = new Color(204,204,204);
        
        
        //set defalut color to pan on run time
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        //iconpetugas
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        menuBeranda = new javax.swing.JLabel();
        menuSiswa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menuKelas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuPembayaran = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        menuAngkatan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuTentang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        menuKeluar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        totalSiswa = new javax.swing.JLabel();
        totalKelas = new javax.swing.JLabel();
        jmlhJurusan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelExit = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        menuName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        profilPetugas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(25, 72, 77));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBeranda.setBackground(new java.awt.Color(25, 72, 77));
        panelBeranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBerandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBerandaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBerandaMousePressed(evt);
            }
        });

        menuBeranda.setBackground(new java.awt.Color(131, 191, 198));
        menuBeranda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuBeranda.setForeground(new java.awt.Color(255, 255, 255));
        menuBeranda.setText("BERANDA");

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(menuBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(panelBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 30));

        menuSiswa.setBackground(new java.awt.Color(25, 72, 77));
        menuSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuSiswaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSiswaMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(131, 191, 198));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISWA");

        javax.swing.GroupLayout menuSiswaLayout = new javax.swing.GroupLayout(menuSiswa);
        menuSiswa.setLayout(menuSiswaLayout);
        menuSiswaLayout.setHorizontalGroup(
            menuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSiswaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        menuSiswaLayout.setVerticalGroup(
            menuSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        menuKelas.setBackground(new java.awt.Color(25, 72, 77));
        menuKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuKelasMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuKelasMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(131, 191, 198));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KELAS");

        javax.swing.GroupLayout menuKelasLayout = new javax.swing.GroupLayout(menuKelas);
        menuKelas.setLayout(menuKelasLayout);
        menuKelasLayout.setHorizontalGroup(
            menuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKelasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        menuKelasLayout.setVerticalGroup(
            menuKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, -1));

        menuPembayaran.setBackground(new java.awt.Color(25, 72, 77));
        menuPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPembayaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPembayaranMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuPembayaranMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(131, 191, 198));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PEMBAYARAN");

        javax.swing.GroupLayout menuPembayaranLayout = new javax.swing.GroupLayout(menuPembayaran);
        menuPembayaran.setLayout(menuPembayaranLayout);
        menuPembayaranLayout.setHorizontalGroup(
            menuPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPembayaranLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        menuPembayaranLayout.setVerticalGroup(
            menuPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, -1));

        menuAngkatan.setBackground(new java.awt.Color(25, 72, 77));
        menuAngkatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAngkatanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuAngkatanMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuAngkatanMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(131, 191, 198));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ANGKATAN");

        javax.swing.GroupLayout menuAngkatanLayout = new javax.swing.GroupLayout(menuAngkatan);
        menuAngkatan.setLayout(menuAngkatanLayout);
        menuAngkatanLayout.setHorizontalGroup(
            menuAngkatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAngkatanLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        menuAngkatanLayout.setVerticalGroup(
            menuAngkatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuAngkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, -1));

        menuTentang.setBackground(new java.awt.Color(25, 72, 77));
        menuTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuTentangMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuTentangMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(131, 191, 198));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TENTANG");

        javax.swing.GroupLayout menuTentangLayout = new javax.swing.GroupLayout(menuTentang);
        menuTentang.setLayout(menuTentangLayout);
        menuTentangLayout.setHorizontalGroup(
            menuTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTentangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        menuTentangLayout.setVerticalGroup(
            menuTentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, -1));

        menuKeluar.setBackground(new java.awt.Color(25, 72, 77));
        menuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuKeluarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuKeluarMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(131, 191, 198));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KELUAR");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuKeluarLayout = new javax.swing.GroupLayout(menuKeluar);
        menuKeluar.setLayout(menuKeluarLayout);
        menuKeluarLayout.setHorizontalGroup(
            menuKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKeluarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        menuKeluarLayout.setVerticalGroup(
            menuKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(menuKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 430));

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        totalSiswa.setForeground(new java.awt.Color(0, 51, 51));
        totalSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSiswa.setText("0");

        totalKelas.setForeground(new java.awt.Color(0, 51, 51));
        totalKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKelas.setText("0");

        jmlhJurusan.setForeground(new java.awt.Color(0, 51, 51));
        jmlhJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlhJurusan.setText("0");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/beranda.png"))); // NOI18N

        jDesktopPane2.setLayer(totalSiswa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(totalKelas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jmlhJurusan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(jmlhJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(totalKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(totalSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel10)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlhJurusan)
                    .addComponent(totalKelas)
                    .addComponent(totalSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 900, 480));

        panelExit.setBackground(new java.awt.Color(255, 255, 255));
        panelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelExitMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelExitMousePressed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit.setText("X");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelExitLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(Exit)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 30, 30));

        menuName.setBackground(new java.awt.Color(255, 255, 255));
        menuName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        menuName.setForeground(new java.awt.Color(0, 102, 102));
        menuName.setText("BERANDA");
        getContentPane().add(menuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Petugas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, -1, -1));

        profilPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/iconPetugas.png"))); // NOI18N
        getContentPane().add(profilPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/backgroudDB.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
    }//GEN-LAST:event_formWindowOpened

    private void panelBerandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Beranda beranda = new Beranda();
        jDesktopPane2.add(beranda).setVisible(true);
        
    }//GEN-LAST:event_panelBerandaMouseClicked

    private void panelBerandaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(ClickedColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("BERANDA");
    }//GEN-LAST:event_panelBerandaMousePressed

    private void menuSiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(ClickedColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("SISWA");
    }//GEN-LAST:event_menuSiswaMousePressed

    private void menuKelasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMousePressed
        // TODO add your handling code here:
        menuKelas.setBackground(ClickedColor);
        panelBeranda.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("KELAS");
    }//GEN-LAST:event_menuKelasMousePressed

    private void menuPembayaranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPembayaranMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(ClickedColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("PEMBAYARAN");
    }//GEN-LAST:event_menuPembayaranMousePressed

    private void menuAngkatanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAngkatanMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(ClickedColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("ANGKATAN");
    }//GEN-LAST:event_menuAngkatanMousePressed

    private void menuTentangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTentangMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(ClickedColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
        
        menuName.setText("TENTANG APLIKASI");
    }//GEN-LAST:event_menuTentangMousePressed

    private void menuKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMousePressed
        // TODO add your handling code here:
        
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(ClickedColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuKeluarMousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void menuKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMouseClicked
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
        
        
    }//GEN-LAST:event_menuKeluarMouseClicked

    private void menuSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Siswa siswa = new Siswa();
        jDesktopPane2.add(siswa).setVisible(true);
        
    }//GEN-LAST:event_menuSiswaMouseClicked

    private void menuKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Kelas kelas = new Kelas();
        jDesktopPane2.add(kelas).setVisible(true);
        
    }//GEN-LAST:event_menuKelasMouseClicked

    private void menuAngkatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAngkatanMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Angkatan spp1 = new Angkatan();
        jDesktopPane2.add(spp1).setVisible(true);
    }//GEN-LAST:event_menuAngkatanMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitMouseClicked

    private void menuTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTentangMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Tentang tentang = new Tentang();
        jDesktopPane2.add(tentang).setVisible(true);
    }//GEN-LAST:event_menuTentangMouseClicked

    private void menuPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPembayaranMouseClicked
        // TODO add your handling code here:
        jDesktopPane2.removeAll();
        Pembayaran pembayaran = new Pembayaran();
        jDesktopPane2.add(pembayaran).setVisible(true);
    }//GEN-LAST:event_menuPembayaranMouseClicked

    private void panelBerandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBerandaMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(ClickedColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_panelBerandaMouseEntered

    private void menuSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSiswaMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(ClickedColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuSiswaMouseEntered

    private void menuKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKelasMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(ClickedColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuKelasMouseEntered

    private void menuPembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPembayaranMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(ClickedColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuPembayaranMouseEntered

    private void menuAngkatanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAngkatanMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(ClickedColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);        
    }//GEN-LAST:event_menuAngkatanMouseEntered

    private void menuTentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTentangMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(ClickedColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuTentangMouseEntered

    private void menuKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuKeluarMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(ClickedColor);
        panelExit.setBackground(DefaultColor2);
    }//GEN-LAST:event_menuKeluarMouseEntered

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(ClickedColor);
    }//GEN-LAST:event_ExitMousePressed

    private void panelExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelExitMousePressed

    private void panelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseEntered
        // TODO add your handling code here:
        panelBeranda.setBackground(DefaultColor);
        menuKelas.setBackground(DefaultColor);
        menuSiswa.setBackground(DefaultColor);
        menuPembayaran.setBackground(DefaultColor);
        menuAngkatan.setBackground(DefaultColor);
        menuTentang.setBackground(DefaultColor);
        menuKeluar.setBackground(DefaultColor);
        panelExit.setBackground(ClickedColor2);
    }//GEN-LAST:event_panelExitMouseEntered

    private void panelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelExitMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jmlhJurusan;
    private javax.swing.JPanel menuAngkatan;
    private javax.swing.JLabel menuBeranda;
    private javax.swing.JPanel menuKelas;
    private javax.swing.JPanel menuKeluar;
    private javax.swing.JLabel menuName;
    private javax.swing.JPanel menuPembayaran;
    private javax.swing.JPanel menuSiswa;
    private javax.swing.JPanel menuTentang;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelExit;
    private javax.swing.JLabel profilPetugas;
    private javax.swing.JLabel totalKelas;
    private javax.swing.JLabel totalSiswa;
    // End of variables declaration//GEN-END:variables
   
    
}
