/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import koneksi.*;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Kelas extends javax.swing.JInternalFrame {

    Page page = new Page();
    Koneksi koneksi = new Koneksi();
    
    public Kelas() {
        initComponents();
        koneksi.model = (DefaultTableModel) tableKelas.getModel();
        koneksi.CreateKoneksi();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frmId = new javax.swing.JTextField();
        frmKelas = new javax.swing.JTextField();
        frmJurusan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();
        btnBatal = new javax.swing.JButton();

        setBackground(new java.awt.Color(45, 116, 124));
        setPreferredSize(new java.awt.Dimension(900, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jurusan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 120, -1, -1));

        frmId.setForeground(new java.awt.Color(0, 102, 102));
        frmId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                frmIdMouseClicked(evt);
            }
        });
        frmId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmIdActionPerformed(evt);
            }
        });
        getContentPane().add(frmId, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 35, 200, -1));

        frmKelas.setForeground(new java.awt.Color(0, 102, 102));
        frmKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmKelasActionPerformed(evt);
            }
        });
        getContentPane().add(frmKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 77, 200, -1));

        frmJurusan.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(frmJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 117, 200, -1));

        btnKembali.setForeground(new java.awt.Color(0, 102, 102));
        btnKembali.setText("kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        btnTambah.setForeground(new java.awt.Color(0, 102, 102));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        btnHapus.setForeground(new java.awt.Color(0, 102, 102));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        btnSimpan.setForeground(new java.awt.Color(0, 102, 102));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        btnEdit.setForeground(new java.awt.Color(0, 102, 102));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, -1));

        tableKelas.setForeground(new java.awt.Color(0, 102, 102));
        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Kelas", "Jurusan"
            }
        ));
        tableKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKelasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKelas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 680, 180));

        btnBatal.setForeground(new java.awt.Color(0, 102, 102));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // Starting Form
        frmId.setEnabled(false);
        frmKelas.setEnabled(false);
        frmJurusan.setEnabled(false);
        btnTambah.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        readData();
        findId();
        
    }                                                                      
                         
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void frmIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frmIdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_frmIdMouseClicked

    private void frmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmIdActionPerformed

    private void frmKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmKelasActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        frmId.setEnabled(true);
        frmKelas.setEnabled(true);
        frmJurusan.setEnabled(true);
        btnTambah.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        koneksi.statusSimpan = true;
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        dispose();  
        page.halamanDashboard();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tableKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKelasMouseClicked
        // TODO add your handling code here:
        mouseClicked();
    }//GEN-LAST:event_tableKelasMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editData();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Kelas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField frmId;
    private javax.swing.JTextField frmJurusan;
    private javax.swing.JTextField frmKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKelas;
    // End of variables declaration//GEN-END:variables

    // save Data terdapat query untuk menyimpan dan mengupdate data
     private void saveData()
    {
        if (frmId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Id", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }else if (frmKelas.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Kelas", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else if (frmJurusan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukkan Jurusan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            if (koneksi.statusSimpan == true) {
                try {
                    koneksi.command.executeUpdate("insert into kelas values ('"
                           + frmId.getText() + "','"
                           + frmKelas.getText() + "','"
                           + frmJurusan.getText() + "')");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Insert Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                        
            } else {
                try {
                    koneksi.command.executeUpdate("update kelas set nama_kelas='" + frmKelas.getText() + "', jurusan = '"+ frmJurusan.getText() +"' where id_kelas = " + frmId.getText());
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Update Gagal","Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            resetForm();
            readData();
        }
    }
    
    
    
    
    private void editData()
    {
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
        btnHapus.setEnabled(false);
        frmId.setEnabled(false);
        frmKelas.setEnabled(true);
        frmJurusan.setEnabled(true);
        koneksi.statusSimpan = false;
    }
    
    private void hapusData()
    {
        int answer = JOptionPane.showOptionDialog(null, "Delete this one ?", "Alert", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (answer == JOptionPane.YES_OPTION) {
            try {
                koneksi.command.executeUpdate("delete from kelas where id_kelas=" + frmId.getText());
                koneksi.model.removeRow(tableKelas.getSelectedRow());
                resetForm();
                readData();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal Menghapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }
    
    private void resetForm()
    {
        frmId.setEnabled(false);
        frmKelas.setEnabled(false);
        frmJurusan.setEnabled(false);
        btnTambah.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        frmId.setText(null);
        frmKelas.setText(null);
        frmJurusan.setText(null);
        koneksi.statusSimpan = false;
    }
    
    private void readData()
    {
        try {
            koneksi.result = koneksi.command.executeQuery("select * from kelas");
                koneksi.model.setRowCount(0);
                koneksi.model.fireTableDataChanged();
                while (koneksi.result.next()) {
                koneksi.model.addRow(new Object[]{
                    koneksi.result.getString(1),
                    koneksi.result.getString(2),
                    koneksi.result.getString(3),
                   
                });
            }
        } catch (SQLException e) {
            // TODO: handle exception
                JOptionPane.showMessageDialog(this, "Database Gagal","Information", JOptionPane.INFORMATION_MESSAGE);
        }   
    }
    
    private void mouseClicked()
    {
        btnTambah.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnEdit.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
        frmId.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(),0).toString());
        frmKelas.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(),1).toString());
        frmJurusan.setText(tableKelas.getValueAt(tableKelas.getSelectedRow(),2).toString());
    }
    
    private void findId()
    {
        try {
            koneksi.result = koneksi.command.executeQuery("SELECT * FROM kelas ORDER BY id_kelas DESC LIMIT 1");
            System.out.println(koneksi.result);
        } catch (Exception e) {
            System.out.println("ID GAGAL DITEMUKAN");
        }
    }
    
}
