/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import koneksi.*;

/**
 *
 * @author Hafiz
 */
public class Siswa extends javax.swing.JFrame {

    /**
     * Creates new form Siswa
     */
    private Koneksi koneksi = new Koneksi();
    private Page page = new Page();
    public Siswa() {
        initComponents();
        koneksi.model = (DefaultTableModel) tableSiswa.getModel();
        koneksi.CreateKoneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSiswa = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        frmAngkatan = new javax.swing.JComboBox<>();
        frmKelas = new javax.swing.JComboBox<>();
        frmNama = new javax.swing.JTextField();
        frmNIS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        frmAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        frmKontak = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSiswa.setBackground(new java.awt.Color(45, 116, 124));
        panelSiswa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelSiswa.setForeground(new java.awt.Color(0, 102, 102));
        panelSiswa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS");
        panelSiswa.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        panelSiswa.add(frmAngkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));

        panelSiswa.add(frmKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, -1));
        panelSiswa.add(frmNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, -1));
        panelSiswa.add(frmNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DATA SISWA");
        panelSiswa.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        panelSiswa.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 37, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Angkatan");
        panelSiswa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kelas");
        panelSiswa.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 37, -1));

        btnBatal.setText("Batal");
        panelSiswa.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        btnHapus.setText("Hapus");
        panelSiswa.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        btnEdit.setText("Edit");
        panelSiswa.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btnSimpan.setText("Simpan");
        panelSiswa.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        panelSiswa.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btnCari.setText("Cari");
        panelSiswa.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        panelSiswa.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 145, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cari Berdasarkan NIS");
        panelSiswa.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari");
        panelSiswa.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 33, -1));

        frmAlamat.setColumns(20);
        frmAlamat.setRows(5);
        jScrollPane2.setViewportView(frmAlamat);

        panelSiswa.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 230, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        panelSiswa.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));
        panelSiswa.add(frmKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 140, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No Telepon");
        panelSiswa.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "NIS", "Nama", "Kelas", "Angkatan"
            }
        ));
        jScrollPane1.setViewportView(tableSiswa);

        panelSiswa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 850, 160));

        getContentPane().add(panelSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        setSize(new java.awt.Dimension(896, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextArea frmAlamat;
    private javax.swing.JComboBox<String> frmAngkatan;
    private javax.swing.JComboBox<String> frmKelas;
    private javax.swing.JTextField frmKontak;
    private javax.swing.JTextField frmNIS;
    private javax.swing.JTextField frmNama;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelSiswa;
    private javax.swing.JTable tableSiswa;
    // End of variables declaration//GEN-END:variables
}
